name: Containers-ci-cd

on:
  push:
    branches:
      - 'develop**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup complier
        uses: rlalik/setup-cpp-compiler@master
        with:
            compiler: latest
      - name: Build static library
        run: cd src
        run: make containers.a

