name: Containers-ci-cd

on:
  push:
    branches:
      - 'develop**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup complier
        uses: rlalik/setup-cpp-compiler@master
        with:
          matrix:
            compiler: [ g++-11, clang++-11 ]
      - name: Build static library
        run: make containers.a

